// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend-v2/internal/biz"
	"backend-v2/internal/conf"
	"backend-v2/internal/data"
	"backend-v2/internal/server"
	"backend-v2/internal/service"
)

// Injectors from wire.go:

func initApp(bc *conf.Bootstrap) (*server.Server, func(), error) {
	db := data.NewDB(bc)
	client := data.NewRedis(bc)
	dataData, cleanup, err := data.NewData(db, client)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepo, bc)
	exchangeService := service.NewExchangeService(userUsecase)
	grpcServer := server.NewGRPCServer(bc, exchangeService)
	engine := server.NewHTTPServer(bc, exchangeService)
	serverServer := server.NewServer(grpcServer, engine, bc)
	return serverServer, func() {
		cleanup()
	}, nil
}
